`timescale 1ns/1ps
`include "railway_defines.vh"
`include "railway_pkg.vh"

module railway_top
(
    input clk,
    input reset,

    input train_request,
    input [5:0] train_id,
    input [2:0] entry_track,
    input direction,
    input [1:0] train_type,
    input emergency_flag,
    input [7:0] timestamp,

    input track_busy,
    input signal_fault,

    output signal_red,
    output signal_yellow,
    output signal_green,

    output switch_left,
    output switch_right,
    output train_move
);


//--------------------------------------------------
// Internal Wires
//--------------------------------------------------

wire [31:0] request_packet;
wire request_valid;
wire error_flag;

wire [31:0] fifo_packet;
wire fifo_empty;
wire fifo_read_enable;

wire [31:0] selected_packet;
wire selected_valid;

wire [4:0] platform_number;
wire [4:0] route_number;
wire route_valid;

wire [4:0] safe_platform;
wire [4:0] safe_route;

wire safe_valid;

wire safety_error;

wire route_enable;
wire route_ready;
wire route_locked;

wire train_departed;
wire system_running;
wire [7:0] train_count;

wire conflict_detected;
wire [4:0] conflict_route;
wire route_safe;

//--------------------------------------------------
// Deadlock Prevention Signals
//--------------------------------------------------
// deadlock_detected : Indicates that a deadlock
//                     condition has been detected.
//
// blocked_route     : Stores the route that caused
//                     the deadlock condition.
//
// release_required  : Requests the route lock manager
//                     to release the currently locked route.
//
// waiting_condition : Indicates that a valid route
//                     request is waiting for an already
//                     locked/active route.
//--------------------------------------------------

wire deadlock_detected;
wire [4:0] blocked_route;
wire release_required;
wire waiting_condition;

//--------------------------------------------------
// Waiting Condition Generation
//--------------------------------------------------
// A waiting condition occurs when a valid route
// request is trying to use a route that is already
// locked/active.
//
// This signal is used by deadlock_prevention.v.
//--------------------------------------------------

assign waiting_condition =
       route_valid &&
       route_locked &&
       (route_number == safe_route);


//--------------------------------------------------
// Generate Route Enable
//--------------------------------------------------
// Enable the route only when all safety conditions
// are satisfied.
//
// blocked_route == 0 means that no route is currently
// blocked by the deadlock-prevention logic.
//
// Otherwise, the requested route must be different
// from the blocked route.
//--------------------------------------------------

assign route_enable =
       safe_valid &&
       route_safe &&
       !conflict_detected &&
       !deadlock_detected &&
       !error_flag &&
       !safety_error &&
       (conflict_route == 5'd0) &&
       ((blocked_route == 5'd0) ||
        (route_number != blocked_route));
//--------------------------------------------------
// Train Request Manager
//--------------------------------------------------

train_request_manager U1
(
    .clk(clk),
    .reset(reset),

    .train_request(train_request),

    .train_id(train_id),
    .entry_track(entry_track),
    .direction(direction),
    .train_type(train_type),
    .emergency_flag(emergency_flag),
    .timestamp(timestamp),
    .train_count(train_count),

    .request_packet(request_packet),
    .request_valid(request_valid),
    .error_flag(error_flag)
);


//--------------------------------------------------
// FIFO Request Buffer
//--------------------------------------------------

fifo_request_buffer U_FIFO
(
    .clk(clk),
    .reset(reset),

    // Packet generated by Train Request Manager
    .request_packet_in(request_packet),

    // Indicates that request_packet is valid
    .request_valid(request_valid),

    // Scheduler requests a packet from FIFO
    .read_enable(fifo_read_enable),

    // Packet delivered from FIFO to scheduler
    .packet_out(fifo_packet),

    // FIFO status
    // Indicates whether FIFO contains no packets
    .fifo_empty(fifo_empty)
);


//--------------------------------------------------
// Intelligent Scheduler
//--------------------------------------------------

intelligent_scheduler U3
(
    .clk(clk),
    .reset(reset),

    .fifo_packet(fifo_packet),
    .fifo_empty(fifo_empty),

    .fifo_read_enable(fifo_read_enable),

    .selected_packet(selected_packet),
    .selected_valid(selected_valid)
);


//--------------------------------------------------
// Decision Engine
//--------------------------------------------------

decision_engine U4
(
    .clk(clk),
    .reset(reset),

    .selected_packet(selected_packet),
    .selected_valid(selected_valid),

    .platform_number(platform_number),
    .route_number(route_number),
    .route_valid(route_valid)
);


//--------------------------------------------------
// Safety Integrity Checker
//--------------------------------------------------

safety_integrity_checker U5
(
    .clk(clk),
    .reset(reset),

    .platform_number(platform_number),
    .route_number(route_number),
    .route_valid(route_valid),

    .track_busy(track_busy),
    .route_locked(route_locked),
    .signal_fault(signal_fault),

    .safe_platform(safe_platform),
    .safe_route(safe_route),

    .safe_valid(safe_valid),
    .safety_error(safety_error)
);


//--------------------------------------------------
// Signal Manager
//--------------------------------------------------

signal_manager U6
(
    .clk(clk),
    .reset(reset),

   // .safe_valid(safe_valid),

    .route_enable(route_enable),

    .signal_red(signal_red),
    .signal_yellow(signal_yellow),
    .signal_green(signal_green)
);


//--------------------------------------------------
// Point Switch Controller
//--------------------------------------------------

point_switch_controller U7
(
    .clk(clk),
    .reset(reset),

    .route_enable(route_enable),
    .platform_number(safe_platform),
    .route_ready(route_ready),

    .switch_left(switch_left),
    .switch_right(switch_right)
);


//--------------------------------------------------
// Route Lock Manager
//--------------------------------------------------

route_lock_manager U8
(
    .clk(clk),
    .reset(reset),

    .route_ready(route_ready),
    .release_required(release_required),
    .route_locked(route_locked)
);


//--------------------------------------------------
// Train Movement Controller
//--------------------------------------------------

train_movement_controller U9
(
    .clk(clk),
    .reset(reset),

    .route_locked(route_locked &&
              system_running &&
              !conflict_detected &&
              !deadlock_detected &&
              !safety_error),
    .train_departed(train_departed),

    .move_train(train_move)
);


//--------------------------------------------------
// Monitoring Diagnostic
//--------------------------------------------------

monitoring_diagnostic U10
(
    .clk(clk),
    .reset(reset),

    .train_departed(train_departed),

    .system_running(system_running),

    .train_count(train_count)
);
//--------------------------------------------------
// Mconflict Detector
//--------------------------------------------------


route_conflict_detector U11
(
    .clk(clk),
    .reset(reset),

    .route_request(route_valid),
    .requested_route(route_number),

    .active_route(safe_route),
    .route_locked(route_locked),

    .track_busy(track_busy),

    .conflict_detected(conflict_detected),
    .conflict_route(conflict_route),

    .route_safe(route_safe)
);
 //--------------------------------------------------
// Deadlock prevention
//--------------------------------------------------

deadlock_prevention U12
(
    .clk(clk),
    .reset(reset),

    .route_request(route_valid),
    .route_locked(route_locked),

    .requested_route(route_number),
    .active_route(safe_route),

    .waiting_condition(waiting_condition),

    .deadlock_detected(deadlock_detected),

    .blocked_route(blocked_route),

    .release_required(release_required)
);
endmodule
